### ISSUE TITLE
update Movie and Actor Entities

### ISSUE THREAD

**Issue by Kaloyan-Stankov** [SoundofGoodbye/movie-crawler#9]
Movie(Id,Title,Actors(id),Release date,Genre,Duration,TV show(y/n))
Actor model -> Movies(id),Age, Bio

**Comment by SoundofGoodbye** [comment]
There are already tasks for creating the models so renamed this task to be for updating the Entities for the classes.

**Comment by SoundofGoodbye** [comment]
Account and Movie DTO are linked.
